name: Arton-macOS
options:
  bundleIdPrefix: com.arton
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

packages:
  ArtonCore:
    path: ../ArtonCore

targets:
  Arton-macOS:
    type: application
    platform: macOS
    sources:
      - path: .
        excludes:
          - project.yml
          - "*.xcodeproj"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.arton.macos
        PRODUCT_NAME: Arton
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_GENERATION_MODE: GeneratedFile
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGN_ENTITLEMENTS: Arton.entitlements
        SWIFT_VERSION: "5.9"
        ENABLE_HARDENED_RUNTIME: YES
    dependencies:
      - package: ArtonCore
      - target: ArtonWidgetExtension
        embed: true
    entitlements:
      path: Arton.entitlements

  ArtonWidgetExtension:
    type: app-extension
    platform: macOS
    sources:
      - path: ../Arton-macOS-Widget
        excludes:
          - project.yml
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.arton.macos.widget
        INFOPLIST_FILE: ../Arton-macOS-Widget/Info.plist
        CODE_SIGN_ENTITLEMENTS: ../Arton-macOS-Widget/ArtonWidgetExtension.entitlements
        SWIFT_VERSION: "5.9"
        GENERATE_INFOPLIST_FILE: YES
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
        ASSETCATALOG_COMPILER_WIDGET_BACKGROUND_COLOR_NAME: WidgetBackground
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    dependencies:
      - package: ArtonCore
