name: ArtonWidgetExtension
options:
  bundleIdPrefix: com.arton
  deploymentTarget:
    iOS: "17.0"

targets:
  ArtonWidgetExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: .
        excludes:
          - project.yml
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.arton.ios.widget
        INFOPLIST_FILE: Info.plist
        CODE_SIGN_ENTITLEMENTS: ArtonWidgetExtension.entitlements
        SWIFT_VERSION: "5.9"
        GENERATE_INFOPLIST_FILE: YES
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
        ASSETCATALOG_COMPILER_WIDGET_BACKGROUND_COLOR_NAME: WidgetBackground
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    entitlements:
      path: ArtonWidgetExtension.entitlements
      properties:
        com.apple.developer.icloud-container-identifiers:
          - iCloud.com.arton.galleries
        com.apple.developer.icloud-services:
          - CloudDocuments
        com.apple.developer.ubiquity-container-identifiers:
          - iCloud.com.arton.galleries
        com.apple.security.application-groups:
          - group.com.arton.shared
