name: Arton-iOS
options:
  bundleIdPrefix: com.arton
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

packages:
  ArtonCore:
    path: ../ArtonCore

targets:
  Arton-iOS:
    type: application
    platform: iOS
    sources:
      - path: .
        excludes:
          - project.yml
          - "*.xcodeproj"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.arton.ios
        PRODUCT_NAME: Arton
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_GENERATION_MODE: GeneratedFile
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGN_ENTITLEMENTS: Arton.entitlements
        SWIFT_VERSION: "5.9"
        TARGETED_DEVICE_FAMILY: "1,2"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: QG3MEYVHMS
    dependencies:
      - package: ArtonCore
      - target: ArtonWidgetExtension
        embed: true
    entitlements:
      path: Arton.entitlements

  ArtonWidgetExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: ../Arton-iOS-Widget
        excludes:
          - project.yml
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.arton.ios.widget
        INFOPLIST_FILE: ../Arton-iOS-Widget/Info.plist
        CODE_SIGN_ENTITLEMENTS: ../Arton-iOS-Widget/ArtonWidgetExtension.entitlements
        SWIFT_VERSION: "5.9"
        GENERATE_INFOPLIST_FILE: YES
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
        ASSETCATALOG_COMPILER_WIDGET_BACKGROUND_COLOR_NAME: WidgetBackground
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: QG3MEYVHMS
    dependencies:
      - package: ArtonCore
